### ISSUE TITLE
Acções para quando Hacktoberfest arrancar

### ISSUE THREAD

**Issue by inesmartins** [As-Raparigas-do-Codigo/jogo-das-profissoes#8]
1. Tornar repo público

2. Ativar Merge Approvers

No ficheiro `.mergify`, colocar seguinte configuração:

```
pull_request_rules:
  - name: Merge do PR requer 2 reviews
    conditions:
      - "approved-reviews-by>=2"
    actions:
      merge:
        method: merge
```

3. Adicionar o banner:

![Screenshot 2021-09-28 at 17 01 06](https://user-images.githubusercontent.com/39055313/135124041-e228df87-4f2d-4204-bfdd-d186dba8d00e.png)
